obstacle_range: 2.0
raytrace_range: 3.5

footprint: [[-0.625, -0.450], [-0.625, 0.450], [0.625, 0.450], [0.625, -0.450]]

static_layer:
  enabled: true
  map_topic: map

obstacle_layer:
  combination_method: 1
  enabled: true
  inf_is_valid: true
  inflation_radius: 0.1
  obstacle_range: 5.0
  raytrace_range: 70
  track_unknown_space: true
  observation_sources: sick 
  sick:
    clearing: true
    data_type: PointCloud2
    marking: true
    sensor_frame: sick_lidar
    topic: /cloud_all_fields_fullframe/filtered